# Generated by Django 3.2.25 on 2024-04-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='mtype',
            field=models.CharField(default='action', max_length=200),
        ),
    ]
