# Generated by Django 3.2.25 on 2024-04-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_mtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='images/noimg.jpg', upload_to='images/'),
        ),
    ]
